# Site settings

title: Real-Time Train Service Matching
description: A UCL Systems Engineering project.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://students.cs.ucl.ac.uk" # the base hostname & protocol for your site
timezone: "Europe/London"

github_username: ucl-team-8

# Build settings

permalink: /blog/:year/:month/:day/:title/
highlighter: rouge
markdown: kramdown
exclude:
  - README.md
  - Gemfile*
  - node_modules
  - package.json
  - bower.json
  - gulpfile.js
  - deploy.sh
  - assets/bower_components

sass:
  sass_dir: assets/scss

# Collections

collections:

defaults:

# Gems

gems:
  - jekyll-redirect-from
